{
 "title": "Grafana_Python_Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "idCelula",
    "query": "SELECT id_celula FROM grafana_python.celula;"
   },
   {
    "name": "ejecucion_desde",
    "query": "select id from executions where id_celula = ${idCelula} order by id desc limit 10"
   },
   {
    "name": "ejecucion_hasta",
    "query": "select id from executions where id_celula = ${idCelula} and id >= ${ejecucion_desde} order by id desc limit 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Resultados por Features",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(if(fe.status = 'passed', 1, 0)) AS 'Passed', SUM(if(fe.status = 'failed', 1, 0)) AS 'Failed' FROM grafana_python.features fe where id_execution >= ${ejecucion_desde} and id_execution <= ${ejecucion_hasta};"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nombre_proyecto Proyecto, nombre_celula Celula, nombre_qa 'Automation QA'  FROM grafana_python.celula where id_celula = ${idCelula};"
    }
   ]
  },
  {
   "title": "Listado de Ejecuciones",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT exe.id, exe.start_datetime as Fec_Inicio, \nCONCAT(TIMESTAMPDIFF(MINUTE,exe.start_datetime, exe.end_datetime),':', \n (TIMESTAMPDIFF(SECOND,exe.start_datetime,exe.end_datetime) - (TIMESTAMPDIFF(MINUTE,exe.start_datetime,exe.end_datetime)*60))) \n\t\t as time_run\n,exe.producto, exe.flujo, exe.browser, \n(SELECT count(*) FROM scenario_executions se where se.id_execution = exe.id and se.scenario_status = 'passed' ) as 'Escenarios Passed',\n(SELECT count(*) FROM scenario_executions se where se.id_execution = exe.id and se.scenario_status = 'failed' ) as 'Escenarios Fail'\nFROM grafana_python.executions exe\ninner join celula cel on cel.id_celula = exe.id_celula\nwhere exe.id >= ${ejecucion_desde} and exe.id <= ${ejecucion_hasta}"
    }
   ]
  },
  {
   "title": "Escenarios por Ejecuciones",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nsum((SELECT count(*) FROM scenario_executions se where se.id_execution = exe.id and se.scenario_status = 'passed' )) as 'Escenarios Passed',\nsum((SELECT count(*) FROM scenario_executions se where se.id_execution = exe.id and se.scenario_status = 'failed' )) as 'Escenarios Fail'\nFROM grafana_python.executions exe\ninner join celula cel on cel.id_celula = exe.id_celula\nwhere exe.id >= ${ejecucion_desde} and exe.id <= ${ejecucion_hasta}"
    }
   ]
  },
  {
   "title": "Features por Ejecución",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT fe.idfeatures,fe.id_execution, CONCAT(TIMESTAMPDIFF(MINUTE,fe.t_inicio,fe.t_fin),':', \n (TIMESTAMPDIFF(SECOND,fe.t_inicio,fe.t_fin) - (TIMESTAMPDIFF(MINUTE,fe.t_inicio,fe.t_fin)*60))) \n\t\t as time_run,fe.nombre_feature, fe.tags_feature, fe.status,\n\t(SELECT count(*) FROM grafana_python.scenario_executions where id_feature = fe.idfeatures \n       and scenario_status = 'passed' ) as 'Escenarios Passed',\n       (SELECT count(*) FROM grafana_python.scenario_executions where id_feature = fe.idfeatures \n       and scenario_status = 'failed' ) as 'Escenarios Failed'\n       FROM grafana_python.executions ex \ninner join celula cel on cel.id_celula = ex.id_celula\ninner join features fe on fe.id_execution = ex.id\ninner join scenario_executions esc on esc.id_feature = fe.idfeatures \nwhere fe.id_execution >= ${ejecucion_desde} and fe.id_execution <= ${ejecucion_hasta}\ngroup by idfeatures;"
    }
   ]
  }
 ]
}